version: "3.9"
services:
  datinggame:
    image: gcr.io/hiring-278615/datinggame
    environment:
      - LOG_LEVEL=info
      - SEQUENCE_COUNT=1000000
      - USER_COUNT=9000
    ports:
      - "9090:9090"
      - "9099:9099"
    container_name: event_server
    networks:
      - app-network
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9090"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  app:
    build: github.com/jordigili/InfatuationSocketServer#main
    container_name: python_server
    networks:
      - app-network
#    depends_on:
#      datinggame:
#        condition: service_healthy

networks:
  app-network:
    driver: bridge