version: "3.9"
services:
  datinggame:
    image: gcr.io/hiring-278615/datinggame
    environment:
      - LOG_LEVEL=info
      - SEQUENCE_COUNT=1000000
      - USER_COUNT=9000
    ports:
      - "9090:9090"
      - "9099:9099"
    container_name: event_server
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "event_server:9090"]
      interval: 5s
      timeout: 2s
      retries: 1
  app:
    build: github.com/jordigili/InfatuationSocketServer#main
    container_name: python_server
    networks:
      - app-network
    depends_on:
      datinggame:
        condition: service_healthy

networks:
  app-network:
    driver: bridge